# Generated by Django 4.2.7 on 2023-11-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
